---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
    name: {{ include "controller.fullname" . }}-manage-own-resources
    labels:
        {{- include "controller.labels" . | nindent 8 }}
subjects:
    - kind: ServiceAccount
      name: {{ $.Values.serviceAccount.name }}
      namespace: {{ .Release.Namespace }}
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: {{ include "controller.fullname" . }}-manage-own-resources
