{{ if $.Values.installCRD }}
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.9.2
  creationTimestamp: null
  name: clusterbackupproceduretemplates.riotkit.org
spec:
  group: riotkit.org
  names:
    kind: ClusterBackupProcedureTemplate
    listKind: ClusterBackupProcedureTemplateList
    plural: clusterbackupproceduretemplates
    singular: clusterbackupproceduretemplate
  scope: Cluster
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: ClusterBackupProcedureTemplate is the Schema for the clusterbackupproceduretemplates
          API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: ClusterBackupProcedureTemplateSpec defines the desired state
              of ClusterBackupProcedureTemplate
            properties:
              backup:
                type: string
              image:
                type: string
              restore:
                type: string
            required:
            - backup
            - image
            - restore
            type: object
          status:
            description: ClusterBackupProcedureTemplateStatus defines the observed
              state of ClusterBackupProcedureTemplate
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
{{ end }}
