---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.9.2
  creationTimestamp: null
  name: restoredbackups.riotkit.org
spec:
  group: riotkit.org
  names:
    kind: RestoredBackup
    listKind: RestoredBackupList
    plural: restoredbackups
    singular: restoredbackup
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: RestoredBackup is the Schema for the restoredbackups API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: RestoredBackupSpec defines the desired state of RestoredBackup
            properties:
              foo:
                description: Foo is an example field of RestoredBackup. Edit restoredbackup_types.go
                  to remove/update
                type: string
              scheduledBackupRef:
                properties:
                  name:
                    type: string
                required:
                - name
                type: object
              targetVersion:
                type: string
            required:
            - scheduledBackupRef
            - targetVersion
            type: object
          status:
            description: RestoredBackupStatus defines the observed state of RestoredBackup
            properties:
              podName:
                type: string
              started:
                type: boolean
              succeeded:
                type: boolean
            required:
            - podName
            - started
            - succeeded
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
